scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080
- job_name: apache
  scrape_interval: 5s
  static_configs:
    - targets:
      - victim:80
